### ISSUE TITLE
GPU ran out of memory

### ISSUE THREAD

**Issue by Melvin-leo** [youmi-zym/GO-SLAM#38]
Currently my GPU is 3080 16gb of vram and yet my cuda ran out of memory

```
RuntimeError: CUDA out of memory. Tried to allocate 1.43 GiB (GPU 0; 15.64 GiB total capacity; 2.04 GiB already allocated; 1.40 GiB free; 4.59 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation
```

![image](https://github.com/user-attachments/assets/9ae8857b-9ffe-4661-90ca-3cfec940011d)

Not sure if there are any tips to resolve this error?

**Comment by leavesnight** [comment]
my GPU 4090 RTX 24GB also CUDA out of memory when running EuRoC V202medium, why?

**Comment by leavesnight** [comment]
> my GPU 4090 RTX 24GB also CUDA out of memory when running EuRoC V202medium, why?

I've solved it by using back cuda11.3, this problem happend with cuda11.7
